# Site settings
title: EagleOne
subtitle: by HTML5 UP
email: eaglenumonewhofightwithme@gmail.com
description: A responsive site template designed by HTML5 Up<br /> and released under the Creative Commons.
baseurl: "/EagleOne/#one" # the subpath of your site, e.g. /blog
url: "https://eagleking.github.io" # the base hostname & protocol for your site
author: EagleOne
street_address: 相城区
city: 苏州市
state: 江苏省
zip_code: 215000
country: 中国
phone: 15501697520

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# Social settings
500px_url:
facebook_url:
github_url:
gitlab_url: https://gitlab.com/u/andrewbanchich
googleplus_url: https://plus.google.com/u/0/+AndrewBanchich
instagram_url: https://instagram.com
linkedin_url: https://www.linkedin.com/in/andrew-banchich-a4ba1195
pinterest_url:
slack_url:
twitter_url: https://twitter.com/andrewbanchich

# Build settings
markdown: kramdown
