# Site settings
title: EagleOne
subtitle: by HTML5 UP
email: eaglenumonewhofightwithme@gmail.com
description: 我在这里分享我的技术心得和生活感悟。
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://eagleking.github.io" # the base hostname & protocol for your site
author: EagleOne
street_address: 相城区
city: 苏州市
state: 江苏省
zip_code: 215000
country: 中国
phone: 15501697520

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# Social settings
500px_url:
facebook_url:
github_url:
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: 


# Markdown 处理器
markdown:       kramdown
highlighter:    rouge
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  use_coderay: false

  coderay:
    coderay_wrap: div
    coderay_line_numbers: inline
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: style

redcloth:
  hard_breaks: true


